name: ramachandraa_s_application
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  web: any
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Cabin
      fonts: 
        - asset: assets/fonts/CabinSemiBold.ttf
          weight: 600
        - asset: assets/fonts/CabinRegular.ttf
          weight: 400
        - asset: assets/fonts/CabinMedium.ttf
          weight: 500
        - asset: assets/fonts/CabinBold.ttf
          weight: 700
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Jost
      fonts: 
        - asset: assets/fonts/JostRegular.ttf
          weight: 400
